### ISSUE TITLE
[Feature Suggestion] Support for Cert Based Auth/HTTPS Listeners

### ISSUE THREAD

**Issue by DWSR** [flynnhandley/terraform-provider-hyperv#2]
As a user, I need the ability to authenticate via other mechanisms besides AD/Kerberos. Possible use cases:

- Non-domain environments (i.e. labs, smaller businesses)
- Hostile or assume-breach environments (i.e. remote facilities with no other authentication mechanisms)

An example of how to set this up can be found here: https://4sysops.com/archives/powershell-remoting-over-https-with-a-self-signed-ssl-certificate/

**Comment by flynnhandley** [comment]
Hi @DWSR, thanks for the request.
This looks like an easy one, I think all we need to do is to add support for the -UseSSL switch. Other than that, the end user will need to ensure the environment is configured correctly.

**Comment by flynnhandley** [comment]
I've added the -UseSSL flag. You can set it up like this...

```
provider "hyperv" {
  hypervisor            = "HV01.contoso.local"
  username              = "hv_administrator"
  password              = "Password1234!"
  use_ssl                  = true
}
```
